---
title: "Metodología"
author: "CruzJulian"
csl: apa.csl
output:
  word_document:
    toc: yes
    reference_docx: Plantilla_APA.docx
bibliography: 777_Biblio.bib
---

# Diseño metodológico

La metodología propuesta es de tipo exploratorio y descriptivo con el fin de caracterizar el fenómeno de estudio, e identificando posteriormente las relaciones entre las variables [@van1996manual].


# Muestra

A continuación se presentan los detalles del proceso de selección de los participantes del estudio. Dado que se hace uso de métodos cuantitativos, es necesario establecer una muestra estadística.

## Población objetivo

La población objetivo del estudio corresponde a la totalidad de los estudiantes matriculados en los programas de pregado de la Facultad de Ciencias Humanas de la Universidad Nacional de Colombia sede Bogotá durante el semestre 2018-3. Correspondiente a 4588 personas según el listado de estudiantes activos proporcionado por la oficina de registro.

## Criterios de inclusión y de exclusión

Se excluyen del estudio 

 - Personas que no cuenten con la calidad de estudiante en el semestre 2018-3.
 - Estudiantes de otras facultades.
 - Estudiantes de posgrado y programas distintos al pregrado.

Se incluyen dentro de este estudio

 - Estudiantes matriculados en los programas de pregado de la Facultad de Ciencias Humanas de la Universidad Nacional de Colombia sede Bogotá durante el semestre 2018-3.

## Tamaño de muestra

El tamaño muestral corresponde a la cantidad de sujetos necesarios para garantizar la representantividad de la muestra. En concordancia con los instrumentos a aplicar y el tamaño conocido de la población se hace uso de la siguiente fórmula:

$$n = \frac{N z^2_{1-\alpha/2} p (1-p)}{(N-1) e^2 + z^2_{1-\alpha/2} p (1-p)}$$

con

 - un error $e$ de 3%.
 - una probabilidad hipotética $p$ de 0.5.
 - un nivel de significancia $\alpha$ de 5%.

Con estos parámetros se establece entonces un tamaño de muestra de 810 estudiantes.

## Diseño muestral

El proceso de selección de los participantes es probabilístico. Se trata de un Muestreo Aleatorio Simple (MAS) realizado sobre el listado de estudiantes activos proporcionado por la oficina de registro. El proceso de recolección de la información se realiza por medio de la herramienta de formularios de google.

# Variables

# Métodos estadísticos

A continuación se explican algunos de los métodos estadísticos utilizados para el análisis de los datos recolectados. Esta tarea se lleva a cabo con el fin de establecer de antemano la fiabiidad y los soportes teóricos de dichos análisis.

## Análisis de componentes principales

El Anílisis de Componentes Principales (ACP) [@Jolliffe2002] utiliza herramientas de álgebra lineal para reducir la dimensión de los datos. Cada registro de la base de datos es visto como un punto en el espacio vectorial $p$-dimensional; mediante una traslación y una rotación óptimas la nube de puntos es reubicada en un subespacio de dimensión menor con una pérdida mínima de información.

Este subespacio queda expresado en un número menor de dimensiones $p'$ representadas por sus respectivos ejes. La inercia, varianza multivariada, es la medida de información contenida en la nube de puntos. Al realizar las operaciones mencionadas de rotación y traslación la inercia resultante se distribuye en los nuevos ejes de manera descendente; así, el primer eje recoge la mayor cantidad de inercia lineal presente en la nube de puntos, el segundo la mayor cantidad restante, etc. Cada ejercicio arroja una tabla denominada tabla de autovalores que muestra la cantidad de inercia recogida por cada eje, tanto de manera absoluta como porcentual. Los planos construidos a partir de estos ejes mapean la nube de puntos guardando la mayor cantidad de información posible.

## Consistencia interna

En los casos donde todas las variables son mediciones indirectas distintas de un mismo aspecto no medible, se hace referencia a la propiedad denominada consistencia interna. La consistencia interna consiste en la propiedad de las variables en estar altamente correlacionadas entre sí, lo que indica que están asociadas a un trazo latente. Dado que esta consistencia interna se encuentra reflejada en a estructura de correlación de las variables es posible medirla y analizarla. El Alfa de Cronbach [@Cronbach1951] es una de las medidas más usadas para analizar la consistencia entre variables.

Dados $K$ variables $Y_1, Y_2, ..., Y_K$ y su suma $X = Y_1 + Y_2 + ... + Y_K$, el Alfa de Chronbach está dado por la expresión

$$\alpha = \frac{K}{K-1} \left(1-\frac{\sum_{J = 1}^K S^2_{J_i}}{S^2_T}\right)$$

donde k es el número de elementos del instrumento,la varianza de los totales es $S^2_{T}$ y la varianza del item esta dada por:

$$S^2_{J}=({x_{ij}}-\bar{x}_j)^2)$$


[@Cronbach1963]


## Pruebas de normalidad 

El supuesto de normalidad es el importante en los procesos estadísticos, por ello se debe probar este supuesto, para la  verificación hay diversas pruebas, entre estas se encuentra la prueba de Lilliefors la cual es una modificación de la prueba de bondad de ajuste Kolomogorov- Smirnov.
 
Esta prueba fue desarrollada por Lilliefors y Van Soest en 1967, las hipotesís son:
$$H_{0}= los\, datos\,proceden\, de\, una\, distribución\,normal$$
$$H_{1}= los\, datos\, no\, proceden\, de\, una\, distribución\, normal$$

La prueba de Lilliefors calcula la distribución muestral por medio de la técnica de Monte Carlo, la media de la muestra se obtiene de:

$$M_{x}=\frac{1}{N}\sum_{i}^{N}x_{i}$$
Donde N son el numero de puntuaciones y$x_{i}$ son las puntuaciones 

La varianza de la muestra esta dada por:

$$S^{2}_{x}=\frac{\sum_{i}^{N}(x_{i}-M_{x})^{2}}{N-1}$$
Se calculan las puntuaciones de z de la siguiente manera:
$$Z_{i}=\frac{x_{i}-M_{x}}{S_{x}}  $$

$\varphi(Z_{i})$ son las frecuencias asociadas a las puntuaciones, también se calculan las probabilidades asociada, las cuales se denotan $N(Z_{I})$, para probar una Normal estandar se calculan de la siguiente manera:
$$N(Z_{i})=\int_{-\infty}^{Z_{i}}\frac{1}{\sqrt{2\pi}}exp\left \{-\frac{1}{2}Z_{i}^{2}  \right \}$$ 
El criterio para la prueba de Lilliefors se denota con L y se calcula de la siguiente manera:

$$L=max \left \{ |\varphi(Z_{i})-N(Z_{i})|,|\varphi(Z_{i})-N(Z_{i-1}) \right \}$$
Esto valores se comparan con los valores críticos de la tabla construida por Kolmogorov-Smirnov/Lilliefors, donde se rechaza la hipótesis nula cuando el valor de L es mayor o igual al Valor de la tabla.[@lilliefors]

## Bootstrapping

El bootstrapping es una técnica computacional no paramétrica para hacer inferencia. El bootstrapping difiere del enfoque paramétrico tradicional, la inferencia que emplea grandes números de cálculos repetitivos para estimar la forma de la distribución muestral [@BOOTSTRAPPING].

Se basa en una analogía entre la muestra y la población de la que se extrajo la muestra, la idea es obtener mejores conclusiones de la población para esto Bootstrapping realiza un remuestreo con reemplazo de los datos.

En bootstrapping se trata la muestra como la población y se realiza un Monte Carlo en la muestra, cada remuestreo podria tener puntos de datos originales y otros no, debido a que son con reemplazo.

Los pasos para realizar el bootstrapping  son:

1. Se construye una distribución de probabilidad empirica $\hat{F}(x)$ a partir de muestras,colocando una probabilidad de $\frac{1}{n}$ en cada punto, asi se obtiene lo que seria $F(x)$

1. De $\hat{F}(x)$ se selecciona una muestra de tamaño $n$.

1. Calcular el estadístico de interés $\hat{\theta}$ en el remuestreo para así obtener $\hat{\theta}_{b}$

1. Se repiten los pasos 2 y 3 B veces donde B debe estar entre 50 y 200 para estimar el error estándar de $\hat{\theta}$, si se quieren estimar los intervalos de confianza este valor debe estar por encima de 1000.

1. Se construye una distribución de probabilidad a partir de B, para este caso la probabilidad en cada punto es $\frac{1}{B}$,  esta distribución es la estimación de la distribución muestral de $\hat{\theta}$,$\hat{F}^{*}(\hat{\theta^{*}})$ 


## Modelos de Ecuaciones Estructurales

Según [@Bagozzi2012] los modelos de ecuaciones estructurales son procedimientos estadísticos para probar hipótesis de medición, funcionales, predictivas y causales. Existen dos tipos de modelos de ecuaciones estructurales, los exploratorios y los confirmatorios. Un análisis exploratorio parte de los datos para dar luces respecto a su comportamiento y así componer estructuras de relaciones entre las variables; el PCA antes explicado es un modelo exploratorio. Un análisis confirmatorio parte de un sistema de ecuaciones hipotóticas propuesto por los autores que luego se corroboran (o desestiman) por medio de la estimación de sus parámetros basada en datos.

Adicionalmente, los modelos de ecuaciones estructurales completo teniendo en cuenta a [@ruiz2010modelos], se deben a dos modelos fundamentales, el modelo de media y el modelo de relaciones estructurales. 

El modelo de media permite que cada variable latente esta medida por indicadores observables, de manera que, dependiendo de la relación entre sí se puede identificar que los errores pueden afectar las mediciones de las otras variables o solo influir sobre sí misma. Y el modelo de relaciones estructurales proporciona los efectos y relaciones de variables, adicionalmente presenta los modelos de predicción.

Por lo tanto, en modelos estructurales se permite ajustar las covarianzas entre las variables en vez de ajustar los datos, así que se minimiza la diferencia entre la covarianza observada de la muestra y la covarianza pronosticada por el modelo. 

El ajuste se debe a la siguiente ecuación: $\sum = \sum(\theta)$, donde $\sum$ es la matriz de varianzas y covarianzas poblacional entre las variables observadas, $\theta$ es un vector de parámetros del modelos y $\sum(\theta)$ es la matriz de varianzas y covarianzas derivada como una función de parámetros contenidos en el vector $\theta$.


# Instrumentos


Las variables que se consideran en el estudio están divididas en tres grupos:

## Satisfacción sexual

Se recolecta información de los sujetos asociada al Cuestionario de Satisfacción Sexual de la profesora Rosalba Rodróguez (cita) que mide las dimensiones de reacción emocional y comunicación por medio de las siguentes afirmaciones:

### Reacción emocional

 - Me importa el placer de la persona con la que tengo relaciones sexuales
 - Considero que mis experiencias sexuales son muy placenteras
 - Después de una relación sexual evito el contacto con la persona con quien estuve
 - En la relación sexual finjo tener un orgasmo para que la otra persona se sienta bien
 - He llorado por la inconformidad generada durante mis relaciones sexuales
 - Después de mis prácticas sexuales tengo un profundo sentimiento de soledad
 - Siento temor de decirle a la otra persona lo que me gusta sexualmente
 - Me siento culpable luego de tener una experiencia sexual
 - Me reprocho algunas de mis experiencias sexuales
 - En mis relaciones sexuales suelo concentrarme en la penetración descuidado otros aspectos
 - He notado poco interés hacia mis relaciones sexuales
 - Pienso en otras cosas cuando tengo una práctica sexual
 - Cuando tengo una relación sexual espero que pronto se acabe
 - Suelo preguntarme por qué accedí a tener una relación sexual con alguien
 - Luego de una relación sexual siento como si no hubiera ocurrido
 - Cuando amo tanto a las personas con las que me relaciono sexualmente me obligo a realizar lo que no deseo para satisfacerle
 - Cuando tengo relaciones sexuales cada cual lleva su propio ritmo

### Comunicación

 - Me incomoda manifestar placer
 - En el momento de mis prácticas sexuales me inquieta no alcanzar el orgasmo rápidamente
 - Me considero buen(a) amante
 - Cuando tengo relaciones sexuales el movimiento con la otra persona es sincronizado
 - Converso con la otra persona acerca de lo que nos produce placer
 - Mis relaciones sexuales son apasionadas
 - Mis parejas me definen como buen(a) amante
 - Prolongo mi excitación hasta que la otra persona alcance el orgasmo
 - Con mi pareja cumplimos nuestras expectativas al tener una relación sexual
 - Cuando estoy sexualmente con mi pareja siento una profunda conexión
 - Me entiendo con las personas con quienes tengo relaciones sexuales
 - En mis relaciones sexuales logro desinhibirme por completo
 - Considero que mis relaciones sexuales son muy creativas
 - Después de una relación sexual tengo una sensación de plenitud
 - Me involucro con todos mis sentidos cuando tengo una relación sexual
 - Después de mis prácticas sexuales sonrío plácidamente

## Percepcíon de riesgo sexual

Se indaga sobre las siguientes prácticas y su percepción de riesgo sexual

 - Considero que tener relaciones sexuales sin condón es riesgoso.
 - Corro mayor riesgo al tener relaciones sexuales bajo efectos del alcohol.
 - Me gusta tener relaciones sexuales bajo efectos de sustancias psicoactivas.
 - Puedo tener relaciones sexuales grupales (incluido el intercambio de pareja) de forma segura. 
 - Ofrecer o hacer uso de servicios sexuales no lo considero riesgoso para mi salud.
 - El coito interrumpido es una método de planificación efectivo.
 - Tener relaciones sexuales tres días antes o después de la menstruación es un buen método de planificación natural.
 - La masturbación mutua es una práctica sexual segura.
 - Abstenerme de tener relaciones sexuales es la conducta menos riesgosa frente a mi sexualidad
 - Un embarazo no deseado es el resultado de una conducta sexual riesgosa.
 - Tener conductas sexuales de riesgo aumenta la posibilidad de contraer una ETS o ITS.
 - Al no usar métodos anticonceptivos he llegado a experimentar susto, miedo de alguna consecuencia (embarazos, ITS, ETS)
 - Realizarme examenes médicos periódicos (pruebas de VIH, citologías, entre otros) es una forma de cuidar mi salud sexual.
 - Cuando he tenido relaciones sexuales riesgosas por prevención tomo o induzco a tomar la pastilla del día después (si aplica).
 - Entre menos parejas sexuales tenga, más segura es mi sexualidad.
 - Con mi (ultima) pareja sentimental no he usado condón porque me brinda confianza y seguridad.
 - La infidelidad sexual me parece riesgosa para mi pareja y para mi.
 - No tengo problemas en relacionarme sexualmente con una persona a la que reción conozco.
 - Conocer la historia sexual de mi pareja me da seguridad a la hora de tener sexo 
 - Evito conductas sexuales de riesgo al ser monogamo.
 - Considero que corro menos riesgo sexual al tener relaciones solo con personas conocidas.
 - Me siento más confiado al tener relaciones sexuales con alguien que tenga buena apariencia física. 

## Prácticas

Se pregunta a los participantes por la frecuencia con la que inciden en las siguientes prácticas.

 - He tenido relaciones sexuales sin condón
 - He tenido sexo bajo efectos del alcohol
 - He prácticado sexo bajo efectos de sustancias psicoactivas.
 - He practicado sexo grupal.
 - He ofrecido o hecho uso de servicios sexuales.
 - He sido infiel sexualmente
 - He tenido relaciones sexuales con un recién conocido.
 - He experimentados "sustos" de embarazo o ETS
 - Me he realizado examenes médicos (VIH, citologías, entre otros)
 - He tomado postday / Mi pareja sexual ha tomado post day
 - He prácticado el coito interrumpido
 - Tres días antes o después de la menstruación no uso método barrera
 - Práctico relaciones sexuales solo con personas conocidas
 - Tengo relaciones basada en besos y heteromasturbación
 - Me abstengo de tener relaciones sexuales


# Procedimiento

El análisis estadístico de los datos hace uso de las herramientas presentadas.

## Análisis univariado

El análisis univariado proporciona un panorama general del comportamiento de la muestra por medio de un proceso realizado a cada variable dependiendo del tipo de variable. 

De manera que al analizar las variables tipo factor se observa una tabla de frecuencias con frecuancias relativas y absolutas, se presenta un diagrama de barras y un diagrama de tortas, en ambos casos se muestra la frecuancia relativa convertida en porcentaje.

Por otra parte, el análisis de las variables tipo númericas se presentan los estadisticos fundamentales, como media, máximo, mínimo, desviación estándar y varianza, en una tabla. Y un histograma el cual es tiene un bosquejo de la densidad de la variable.

## Análisis mutivariado

El análisis multivariado de los datos se realiza en dos etapas.

Una primera aproximación agrupa las variables según los aspectos mencionados y en cada aspecto mide la consistencia interna calculando el alpha de Chronbach y ralizando un análisis en componentes principales que muestra las relaciones correspondientes a las variables de cada uno de los aspectos. De esta menera se estructuran:

 - Mediciones de los distintos dominios: actividad sexual, consecuencia, cuidado, elección; a nivel de percepción del riesgo sexual.
 - Mediciones de la presencia en el cotidiano de prácticas sexuales de riesgo.
 - Medición de la satisfacción sexual.
 
Con el fin de evaluar la correlación de la satisfacción sexual con la práctica de actividades sexuales que se perciben como riesgosas.

Una segunda fase aborda el problema por medio de Modelos de Ecuaciones Estructurales, que pueden dar cuenta de una mejor forma de las relaciones de causalidad (bajo supuestos) entre los distintos fenómenos analizados.





# Referencias
